import { act } from "react";
import { webcrypto } from "node:crypto";
import { expect, test, vi } from "vitest";
import { bridge } from "@/shared/api/ipc";
import type { SavedCanvas } from "../shared/workflow-canvas";
import { useCanvasEditor } from "../src/features/workflow-canvas/model/use-canvas-editor";
import { createReactHost } from "./react-host";

test("editor history restores backups and a pending save preserves later edits and conflicts", async () => {
  const backups = new Map<string, string>();
  vi.stubGlobal("crypto", webcrypto);
  vi.stubGlobal("localStorage", { getItem: (key: string) => backups.get(key) ?? null, setItem: (key: string, value: string) => backups.set(key, value), removeItem: (key: string) => backups.delete(key) });
  vi.spyOn(bridge, "loadCanvases").mockResolvedValue([]);
  const save = vi.spyOn(bridge, "saveCanvas").mockImplementation(async (_workspace, canvas) => ({ canvas, revision: "first", path: "/canvases/test.json" }));
  const host = createReactHost();
  const { createRoot } = await import("react-dom/client");
  const root = createRoot(host.container as unknown as Element);
  let editor: ReturnType<typeof useCanvasEditor>;
  function Harness() { editor = useCanvasEditor("workspace", "history", false); return null; }
  try {
    await act(async () => root.render(<Harness />));
    await act(async () => editor!.create("blank"));
    await act(async () => { await editor!.save(); });
    const original = editor!.draft!;
    await act(async () => editor!.edit({ ...original, name: "A" }, { coalesceKey: "name" }));
    await act(async () => editor!.edit({ ...original, name: "AB" }, { coalesceKey: "name" }));
    expect(editor!.canUndo).toBe(true);
    await act(async () => editor!.undo());
    expect(editor!.draft).toEqual(original);
    expect(editor!.dirty).toBe(false);
    expect([...backups.keys()].filter((key) => key.startsWith("ralphy.canvas.draft:"))).toHaveLength(0);
    await act(async () => editor!.redo());
    expect(editor!.draft?.name).toBe("AB");
    expect(editor!.dirty).toBe(true);
    let complete!: (value: SavedCanvas) => void;
    save.mockImplementationOnce(() => new Promise((resolve) => { complete = resolve; }));
    let pending!: Promise<SavedCanvas | null>;
    await act(async () => { pending = editor!.save(); });
    await act(async () => editor!.edit({ ...editor!.draft!, name: "ABC" }, { coalesceKey: "name" }));
    await act(async () => { complete({ canvas: { ...original, name: "AB" }, revision: "second", path: "/canvases/test.json" }); await pending; });
    expect(editor!.draft?.name).toBe("ABC");
    expect(editor!.saved?.revision).toBe("second");
    expect(editor!.dirty).toBe(true);
    const backup = JSON.parse(backups.get("ralphy.canvas.draft:history:workspace")!);
    expect(backup.canvas.name).toBe("ABC");
    expect(backup.saved.revision).toBe("second");
    save.mockRejectedValueOnce(new Error("Changed outside this editor"));
    await act(async () => { await editor!.save(); });
    expect(editor!.error).toContain("Changed outside");
    expect(editor!.draft?.name).toBe("ABC");
    save.mockRejectedValueOnce(new Error("Changed outside this editor"));
    await act(async () => { await editor!.select({ canvas: { ...original, id: "other", name: "Other canvas" }, revision: "other", path: "/canvases/other.json" }); });
    expect(editor!.draft?.id).toBe(original.id);
    expect(editor!.draft?.name).toBe("ABC");
    expect(backups.has("ralphy.canvas.draft:history:workspace")).toBe(true);
    await act(async () => editor!.discard());
    expect(editor!.draft?.name).toBe("AB");
    expect(editor!.canUndo).toBe(false);
    await act(async () => editor!.duplicate());
    expect(editor!.draft?.id).not.toBe(original.id);
    expect(editor!.draft?.name).toBe("AB (copy)");
    expect(editor!.saved).toBeNull();
    expect(editor!.dirty).toBe(true);
    const deferredViewport = editor!.edit;
    await act(async () => editor!.edit({ ...editor!.draft!, name: "Newer edit" }));
    await act(async () => deferredViewport((current) => ({ ...current, viewport: { x: 12, y: 30, zoom: 0.8 } }), { coalesceKey: "viewport" }));
    expect(editor!.draft?.name).toBe("Newer edit");
    expect(editor!.draft?.viewport?.zoom).toBe(0.8);
  } finally { await act(async () => root.unmount()); host.restore(); vi.restoreAllMocks(); vi.unstubAllGlobals(); }
});
