import type { StudioEntry } from "./studio-catalog";
import { visualArtifact, type StudioVisualId } from "./studio-visual-scenes";

const examples: { id: StudioVisualId; name: string; summary: string; tags: string[]; photo: string; body: string }[] = [
  { id: "photo-orbit", name: "A different perspective", summary: "Five photographs circle a quiet editorial title.", tags: ["photo", "carousel", "orbit", "showreel", "motion"], photo: "fashion-editorial.png", body: "Use five images with related lighting and a short two-line title. The photo cards follow a continuous elliptical path while remaining upright. Replace the bundled photo paths with approved project images; preserve object-fit crops that keep subjects readable. Best for portfolio introductions and collection teasers." },
  { id: "cascading-stack", name: "One frame at a time", summary: "A tactile photo stack turns into a continuous reveal.", tags: ["photo", "stack", "polaroid", "showreel", "motion"], photo: "editorial-portrait.png", body: "Use four images and short image labels. Each paper-framed photograph holds at the front, moves aside, and returns behind the stack. Keep the same number of cards or adjust animation delays proportionally. Good for travel memories, behind-the-scenes edits and personal portfolios. The paper frame and label remain editable HTML." },
  { id: "filmstrip", name: "Never stand still", summary: "An angled filmstrip carries a seamless sequence of images.", tags: ["photo", "marquee", "filmstrip", "loop", "motion"], photo: "night-city.png", body: "Use six images in the repeating strip. The markup deliberately repeats the full sequence once for a seamless horizontal loop; replace both copies in the same order. Keep image dimensions and gaps consistent. Change the editorial title and small frame labels. Useful for campaign recaps and varied source aspect ratios." },
  { id: "split-reveal", name: "Two sides, one story", summary: "A moving split reveals two complementary portraits.", tags: ["editorial", "reveal", "diptych", "portrait", "motion"], photo: "fashion-editorial.png", body: "Use two related photographs, not a factual before/after unless they show the same subject. One full-size layer reveals over the other with an animated clipping edge. Keep faces on the readable side of the split and use short foreground text. Suitable for two creative directions or a day/night editorial." },
  { id: "contact-sheet", name: "Collected moments", summary: "Six frames breathe in a staggered contact sheet.", tags: ["photo", "grid", "contact-sheet", "editorial", "motion"], photo: "botanical-study.png", body: "Use six photographs in a stable three-by-two grid. Small staggered movements create rhythm without hiding the complete collection. Replace numbered captions and the closing title. Useful for a moodboard, content-series introduction or campaign recap. Keep a consistent crop and reduce motion for text-heavy images." },
  { id: "type-opener", name: "Make it move", summary: "A two-line title rises through a mask, followed by an accent rule.", tags: ["typography", "title", "editorial", "kinetic", "motion"], photo: "visual-type-opener.svg", body: "Replace the two short title lines, eyebrow and closing note. Each line enters and leaves through an overflow mask; the accent rule follows the type. Keep the title to two short lines to retain the intended timing and scale. This is a text-first opener for an essay, launch film or creator series." },
  { id: "aurora-field", name: "Quiet motion", summary: "Slowly shifting color fields make a soft, atmospheric backdrop.", tags: ["gradient", "background", "ambient", "organic", "motion"], photo: "visual-aurora-field.svg", body: "Use the three independent radial-gradient fields as a reusable background. Recolor their stops and change the foreground title, or remove the title group. Slow movement comes from transforms rather than image generation. Useful behind a title or product still; ensure text remains readable throughout the loop." },
  { id: "orbit-mark", name: "Everything is connected", summary: "Three orbital rings and a moving satellite frame a central mark.", tags: ["geometry", "identity", "orbit", "abstract", "motion"], photo: "visual-orbit-mark.svg", body: "Replace the central disk with an approved logo or keep it abstract. Three rings rotate on separate planes while a small satellite follows an elliptical path. Adjust the colors and closing line. Suitable for a brand ident, chapter break or background accent. Preserve a meaningful static arrangement for reduced-motion viewing." },
];

/** Original motion presets: the preview and reusable artifact share the same HTML and CSS. */
export function studioVisuals(): StudioEntry[] {
  return examples.map((entry) => ({
    id: entry.id, name: entry.name, summary: entry.summary, tags: entry.tags,
    visualId: entry.id, settings: { speed: 1 }, format: "Motion component", duration: "Seamless loop",
    artifact: visualArtifact(entry.id),
    body: `${entry.body}\n\nThe attachment includes complete original HTML and CSS with keyframes and a reduced-motion fallback. Preserve the selected title, format, font scale, weight, text color, background and speed from the attached settings. These values are already applied to the exported composition through CSS custom properties. Wide, square and portrait layouts are supported. Replace sample copy and photo paths, preserve a clean source, then save the edited component. For HyperFrames, adapt the keyframes to a deterministic composition timeline and render a short preview before final export. This component was authored for Ralphy and contains no third-party template code.`,
    preview: { kind: "image", url: `${import.meta.env.BASE_URL}explore/studio/${entry.photo}` },
  }));
}
