#!/usr/bin/env bun
/**
 * Validate done/doing roadmap tasks by checking that cited file paths exist.
 * Emits roadmap/VALIDATION.md with a per-task summary and a section for
 * stale/missing references.
 *
 * Heuristic: extracts every markdown link `](path)` where path matches a
 * repo-internal file shape (cli/, src/, docs/, scripts/, tests/, templates/,
 * landing/, .agents/, etc.). Resolves the path relative to the task file's
 * directory and checks existence.
 */

import { readFileSync, readdirSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join, resolve, dirname, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const ROADMAP = join(ROOT, "roadmap");

const REPO_PATH_PREFIXES = [
  "cli/",
  "src/",
  "docs/",
  "docs-mintlify/",
  "scripts/",
  "tests/",
  "templates/",
  "landing/",
  ".agents/",
  "roadmap/",
  "notes/",
  "ralphy-assets/",
  "workspace/",
  "package.json",
  "tsconfig.json",
];

const STATUSES = ["done", "doing", "cancelled"] as const;
type Status = (typeof STATUSES)[number];

interface Finding {
  taskFile: string;
  taskId: string;
  link: string;
  resolved: string;
  exists: boolean;
}

const findings: Finding[] = [];
const perStatus: Record<Status, { total: number; tasksWithMissing: Set<string> }> = {
  done: { total: 0, tasksWithMissing: new Set() },
  doing: { total: 0, tasksWithMissing: new Set() },
  cancelled: { total: 0, tasksWithMissing: new Set() },
};

function looksLikeRepoPath(p: string): boolean {
  if (p.startsWith("http")) return false;
  if (p.startsWith("#")) return false;
  if (p.startsWith("mailto:")) return false;
  // Strip anchor for the emptiness check
  const noAnchor = p.split("#")[0];
  if (!noAnchor) return false;
  return true;
}

for (const status of STATUSES) {
  const dir = join(ROADMAP, status);
  if (!existsSync(dir)) continue;
  const files = readdirSync(dir).filter((f) => f.endsWith(".md"));
  for (const f of files) {
    const fpath = join(dir, f);
    perStatus[status].total++;
    const body = readFileSync(fpath, "utf-8");
    const taskIdMatch = body.match(/^id:\s+(\d{2}\.\d{2}\.\d{2})/m);
    const taskId = taskIdMatch ? taskIdMatch[1] : f;

    // Extract every markdown link target
    const linkRe = /\]\(([^)\s]+)\)/g;
    let m: RegExpExecArray | null;
    while ((m = linkRe.exec(body))) {
      const link = m[1];
      // strip code-link backticks form etc — none here
      if (!looksLikeRepoPath(link)) continue;
      const linkNoAnchor = link.split("#")[0];
      const resolved = resolve(dirname(fpath), linkNoAnchor);
      const rel = relative(ROOT, resolved);
      const exists = existsSync(resolved);
      findings.push({ taskFile: relative(ROOT, fpath), taskId, link, resolved: rel, exists });
      if (!exists) perStatus[status].tasksWithMissing.add(taskId);
    }
  }
}

const missing = findings.filter((f) => !f.exists);
const present = findings.filter((f) => f.exists);

console.log(`checked ${findings.length} links across ${perStatus.done.total + perStatus.doing.total + perStatus.cancelled.total} tasks`);
console.log(`exists: ${present.length}`);
console.log(`missing: ${missing.length}`);
console.log(`done tasks with missing refs: ${perStatus.done.tasksWithMissing.size} / ${perStatus.done.total}`);
console.log(`doing tasks with missing refs: ${perStatus.doing.tasksWithMissing.size} / ${perStatus.doing.total}`);

// Group missing by task
const missingByTask = new Map<string, Finding[]>();
for (const f of missing) {
  const arr = missingByTask.get(f.taskFile) ?? [];
  arr.push(f);
  missingByTask.set(f.taskFile, arr);
}

// Sort tasks by id
const sortedTasks = [...missingByTask.entries()].sort((a, b) => {
  const idA = a[1][0].taskId;
  const idB = b[1][0].taskId;
  return idA.localeCompare(idB);
});

const lines: string[] = [
  "# Roadmap validation report",
  "",
  `> Generated by \`bun run scripts/validate-roadmap.ts\` on ${new Date().toISOString().slice(0, 10)}.`,
  "",
  "Scope: for every task with status `done`, `doing`, or `cancelled`, extract every markdown link that looks like a repo-internal path (under `cli/`, `src/`, `docs/`, `scripts/`, `tests/`, `templates/`, `landing/`, `.agents/`, etc.) and check that the path resolves to a real file. Anchors are stripped; HTTP and `#anchor`-only links are skipped.",
  "",
  "## Summary",
  "",
  `| Status | Total tasks | Tasks with stale refs |`,
  `|---|---|---|`,
  `| done | ${perStatus.done.total} | ${perStatus.done.tasksWithMissing.size} |`,
  `| doing | ${perStatus.doing.total} | ${perStatus.doing.tasksWithMissing.size} |`,
  `| cancelled | ${perStatus.cancelled.total} | ${perStatus.cancelled.tasksWithMissing.size} |`,
  "",
  `**Total links checked:** ${findings.length}`,
  `**Links resolving:** ${present.length}`,
  `**Links missing:** ${missing.length}`,
  "",
  "## Tasks with at least one stale reference",
  "",
  sortedTasks.length === 0 ? "_None._" : "",
];

for (const [taskFile, items] of sortedTasks) {
  const id = items[0].taskId;
  lines.push(`### ${id} — \`${taskFile}\``);
  lines.push("");
  lines.push("Missing references:");
  lines.push("");
  for (const item of items) {
    lines.push(`- \`${item.link}\` → \`${item.resolved}\``);
  }
  lines.push("");
}

writeFileSync(join(ROADMAP, "VALIDATION.md"), lines.join("\n") + "\n");
console.log("wrote roadmap/VALIDATION.md");
