import { CircleAlert, GitBranch, Unplug, X } from "lucide-react";
import type { CanvasExecutionPlan as Plan } from "../../../../shared/canvas-execution-plan";
import type { CanvasNodeReadiness } from "../../../../shared/canvas-readiness";
import { CANVAS_BUTTON, NODE_ICONS } from "./canvas-chrome";
import { STUDIO_FIELD, STUDIO_LABEL } from "@/entities/generation";

export function CanvasExecutionPlan({ plan, readiness, onFocus, onClose, onAddOutput, onInput, onAsset, disabled }: {
  plan: Plan; readiness: Map<string, CanvasNodeReadiness>; onFocus(id: string): void; onClose(): void; onAddOutput(): void;
  onInput?(id: string, value: string): void; onAsset?(id: string): void; disabled?: boolean;
}) {
  const groups = [
    { title: "Execution order", nodes: plan.nodes, hint: "Each step waits for all its connected inputs. Separate sources can feed the same result.", mode: "included" },
    { title: "Saved result reused", nodes: plan.reused, hint: "A selected variation supplies an existing result. These upstream steps will not run again.", mode: "reused" },
    { title: "Outside this run", nodes: plan.outside, hint: "No path to an Output. Connect this branch to an Output or explicitly run its final node.", mode: "outside" },
  ];
  return <aside className="canvas-catalog flex h-full min-h-0 flex-col bg-card text-ink" aria-label="Execution plan">
    <header className="flex shrink-0 items-center gap-3 border-b border-divider p-4"><GitBranch size={18} /><div className="min-w-0 flex-1"><h2 className="m-0 type-sm font-semibold">Execution plan</h2><p className="m-0 mt-1 type-xs text-muted">{plan.outputs.length} {plan.outputs.length === 1 ? "output" : "outputs"} · {plan.nodes.length} {plan.nodes.length === 1 ? "step" : "steps"} · {plan.sources.length} {plan.sources.length === 1 ? "source" : "sources"}</p></div><button className={CANVAS_BUTTON} type="button" aria-label="Close execution plan" onClick={onClose}><X size={14} /></button></header>
    <div className="flex min-h-0 flex-1 flex-col gap-5 overflow-y-auto p-3">
      {plan.mode === "board" ? <div className="flex flex-col gap-3 rounded-field bg-field p-3"><strong className="type-sm">A board for exploration</strong><p className="m-0 type-xs leading-relaxed text-muted">Add references, compare models and run any step. Its connected inputs run first. Separate experiments can stay unfinished.</p><p className="m-0 type-xs leading-relaxed text-muted">Switch to Workflow when you want to run a repeatable chain from inputs to Output.</p></div> : <>
        {!!plan.sources.some((node) => node.kind === "prompt" || node.kind === "media") && <section className="generation-fields" aria-label="Workflow inputs"><h3 className="m-0 type-sm font-medium">Workflow inputs</h3>{plan.sources.filter((node) => node.kind === "prompt" || node.kind === "media").map((node) => <div className="generation-parameter" key={node.id}><label className={STUDIO_LABEL} htmlFor={`workflow-input-${node.id}`}>{node.title}<small>Required</small></label>{node.kind === "prompt" ? <textarea id={`workflow-input-${node.id}`} className={`${STUDIO_FIELD} generation-prompt`} aria-label={`Workflow input: ${node.title}`} aria-required="true" rows={3} value={node.value} maxLength={20000} disabled={disabled} onChange={(event) => onInput?.(node.id, event.currentTarget.value)} /> : <button className={CANVAS_BUTTON} type="button" disabled={disabled} onClick={() => onAsset?.(node.id)}>{node.config?.asset?.name ?? "Choose a reference"}</button>}</div>)}</section>}
        {!plan.outputs.length && <div className="flex flex-col gap-3 rounded-field bg-field p-3"><strong className="type-sm">Choose where the workflow ends</strong><p className="m-0 type-xs leading-relaxed text-muted">Connect an Output to define the branches included in Run. Individual nodes can still run on their own.</p><button className={CANVAS_BUTTON} type="button" onClick={onAddOutput}>Add Output</button></div>}
      </>}
      {groups.filter((group) => group.nodes.length).map((group) => <section key={group.mode}><div className="mb-2 px-1"><h3 className="m-0 type-xs font-semibold">{group.title} · {group.nodes.length}</h3><p className="mb-0 mt-1 type-xs leading-relaxed text-muted">{group.hint}</p></div><ol className="m-0 flex list-none flex-col gap-1 p-0">{group.nodes.map((node, index) => { const Icon = NODE_ICONS[node.kind]; const state = readiness.get(node.id); return <li key={node.id}><button className="flex w-full items-center gap-2 rounded-field bg-field p-3 text-left hover:bg-row-hover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ink" type="button" onClick={() => onFocus(node.id)}><Icon size={14} className="shrink-0 text-muted" /><span className="flex min-w-0 flex-1 flex-col gap-1"><strong className="truncate type-xs font-medium">{node.title}</strong><span className="type-xs leading-relaxed text-muted">{group.mode === "outside" ? "Not connected to Output" : group.mode === "reused" ? "Skipped · using saved result" : !state?.ready ? state?.issues.join(" · ") : node.kind === "variation" && node.config?.selectedResultId ? "Use selected result" : "Ready"}</span></span>{group.mode === "included" ? !state?.ready ? <CircleAlert size={13} className="shrink-0" /> : <span className="font-code type-mono-xs text-muted">{index + 1}</span> : <Unplug size={13} className="shrink-0 text-muted" />}</button></li>; })}</ol></section>)}
    </div>
  </aside>;
}
