import { useState } from "react";
import { ArrowUpRight, Check, ChevronDown, ChevronRight, Clock3, Expand, FileText, Image, LoaderCircle, Minimize2, Play, Square, X } from "@/shared/ui/icons";
import type { CanvasRun, CanvasRunResult } from "../../../../shared/canvas-runtime";
import { CANVAS_BUTTON } from "./canvas-chrome";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 3 }).format(value);
const stamp = (value: number) => new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
const statusLabel = (run: CanvasRun) => run.mode === "preview" && run.status === "succeeded" ? "Preview ready" : ({ pending: "Queued", running: "Running", succeeded: "Completed", failed: "Failed", cancelled: "Cancelled" })[run.status];

function ResultMedia({ result }: { result: CanvasRunResult }) {
  if (result.previewUrl && result.kind === "image") return <img className="size-full object-contain" src={result.previewUrl} alt={result.label} />;
  if (result.previewUrl && result.kind === "video") return <video className="size-full object-contain" src={result.previewUrl} controls preload="metadata" />;
  if (result.previewUrl && result.kind === "audio") return <audio className="w-full" src={result.previewUrl} controls preload="metadata" />;
  if (result.text) return <p className="m-0 max-h-72 w-full overflow-auto whitespace-pre-wrap p-4 text-left type-sm leading-relaxed">{result.text}</p>;
  return <div className="flex flex-col items-center gap-2 p-6 text-muted"><Image size={24} strokeWidth={1.3} /><span className="type-xs">Preview unavailable</span></div>;
}

export function CanvasRunsPanel({ runs, selectedRun, expanded, onSelectRun, onClose, onExpand, onCancel, onUseResult, onRestore, onExecute, running }: {
  runs: CanvasRun[]; selectedRun?: CanvasRun; expanded: boolean; running: boolean;
  onSelectRun(id: string): void; onClose(): void; onExpand(): void; onCancel(id: string): void;
  onUseResult(result: CanvasRunResult): void; onRestore(run: CanvasRun): void; onExecute(): void;
}) {
  const [compare, setCompare] = useState<string[]>([]);
  const [showSteps, setShowSteps] = useState(false);
  const allResults = [...new Map((selectedRun?.nodes.flatMap((node) => node.results) ?? []).map((result) => [result.id, result])).values()];
  const results = expanded && compare.length > 0 ? allResults.filter((result) => compare.includes(result.id)) : allResults;
  const estimateNodes = selectedRun?.nodes.filter((node) => node.estimatedCostUsd !== null) ?? [];
  const estimate = estimateNodes.reduce((total, node) => total + (node.estimatedCostUsd ?? 0), 0);
  const unpricedModels = selectedRun?.nodes.filter((entry) => entry.estimatedCostUsd === null && selectedRun.snapshot.nodes.some((node) => node.id === entry.nodeId && node.kind === "model")).length ?? 0;
  return <aside className={`canvas-run-panel flex min-h-0 flex-col border-l border-divider bg-panel ${expanded ? "absolute inset-0 z-surface-overlay" : "w-canvas-inspector shrink-0"}`} aria-label="Canvas runs and results">
    <header className="flex h-14 shrink-0 items-center gap-2 border-b border-divider px-4"><Clock3 size={15} /><h2 className="m-0 flex-1 type-sm font-medium">Runs & results</h2><button className={CANVAS_BUTTON} type="button" aria-label={expanded ? "Restore results panel" : "Expand results"} onClick={onExpand}>{expanded ? <Minimize2 size={13} /> : <Expand size={13} />}</button><button className={CANVAS_BUTTON} type="button" aria-label="Close results" onClick={onClose}><X size={13} /></button></header>
    {!runs.length ? <div className="flex flex-1 flex-col items-center justify-center gap-4 p-6 text-center"><div className="rounded-inner bg-field p-4"><Play size={24} strokeWidth={1.2} /></div><h3 className="m-0 type-lg font-medium">Every run, a new direction.</h3><p className="m-0 type-sm leading-relaxed text-muted">Preview the workflow to check its inputs and estimated cost. Generated variations and past runs will live here.</p></div> : <div className={`flex min-h-0 flex-1 ${expanded ? "flex-row" : "flex-col"}`}>
      <nav className={`flex shrink-0 gap-2 overflow-auto p-3 ${expanded ? "w-56 flex-col border-r border-divider" : "max-h-36 flex-col border-b border-divider"}`} aria-label="Run history">
        {runs.map((run, index) => <button key={run.id} className={`flex shrink-0 items-center gap-3 rounded-control p-3 text-left type-xs focus-visible:outline-2 focus-visible:outline-ink ${selectedRun?.id === run.id ? "bg-field text-ink" : "text-muted hover:bg-row-hover"}`} type="button" aria-pressed={selectedRun?.id === run.id} onClick={() => { setCompare([]); onSelectRun(run.id); }}><span className="font-code type-mono-xs">{String(runs.length - index).padStart(2, "0")}</span><span className="min-w-0 flex-1"><strong className="block font-medium">{run.mode === "preview" ? "Workflow preview" : "Generation"}</strong><small className="mt-1 block text-muted">{statusLabel(run)} · {stamp(run.startedAt)}</small></span>{run.status === "running" ? <LoaderCircle size={12} className="animate-spin motion-reduce:animate-none" /> : <ChevronRight size={12} />}</button>)}
      </nav>
      {selectedRun && <div className="min-h-0 min-w-0 flex-1 overflow-auto p-4">
        <div className="mb-4 flex flex-wrap items-center gap-2"><span className="rounded-control bg-field px-2 py-1 type-xs">{statusLabel(selectedRun)}</span><span className="flex-1 type-xs text-muted">{selectedRun.endedAt ? `${Math.max(0, (selectedRun.endedAt - selectedRun.startedAt) / 1000).toFixed(1)}s` : "In progress"}</span>{["running", "pending"].includes(selectedRun.status) && <button className={CANVAS_BUTTON} type="button" onClick={() => onCancel(selectedRun.id)}><Square size={11} />Stop</button>}<button className={CANVAS_BUTTON} type="button" disabled={running} onClick={() => onRestore(selectedRun)} title="Load this run’s workflow as an editable draft"><ArrowUpRight size={12} />Reuse setup</button></div>
        {selectedRun.error && <p className="rounded-field bg-failure p-3 type-sm leading-relaxed text-failure-ink" role="alert">{selectedRun.error}</p>}
        {selectedRun.mode === "preview" && <div className="mb-4 rounded-inner bg-field p-4"><span className="type-xs text-muted">{unpricedModels && estimateNodes.length ? "Partial generation estimate" : "Estimated generation cost"}</span><strong className="mt-2 block type-xl font-medium">{estimateNodes.length ? money(estimate) : "Unavailable"}</strong>{unpricedModels > 0 && <span className="type-xs text-muted">{unpricedModels} model {unpricedModels === 1 ? "step is" : "steps are"} not included.</span>}<p className="mb-3 mt-2 type-xs leading-relaxed text-muted">A preview checks the saved workflow. Providers determine the final charge when you generate.</p>{selectedRun.status === "succeeded" && <button className={`${CANVAS_BUTTON} bg-brand text-brand-ink hover:bg-brand`} type="button" disabled={running} onClick={onExecute}><Play size={12} />Generate current workflow</button>}</div>}
        <button className="mb-3 flex w-full items-center gap-2 bg-transparent p-0 type-xs text-muted" type="button" aria-expanded={showSteps} onClick={() => setShowSteps((value) => !value)}><ChevronDown size={12} className={showSteps ? "" : "-rotate-90"} />{selectedRun.nodes.length} workflow steps</button>
        {showSteps && <ol className="m-0 mb-5 flex list-none flex-col gap-2 p-0">{selectedRun.nodes.map((node, index) => <li key={node.nodeId} className="flex items-start gap-2 type-xs"><span className="flex size-5 shrink-0 items-center justify-center rounded-full bg-field text-muted">{node.status === "succeeded" ? <Check size={11} /> : node.status === "running" ? <LoaderCircle size={11} className="animate-spin motion-reduce:animate-none" /> : index + 1}</span><span className="min-w-0 flex-1 pt-0.5"><strong className="font-medium">{selectedRun.snapshot.nodes.find((item) => item.id === node.nodeId)?.title ?? "Node"}</strong>{node.error && <small className="mt-1 block leading-relaxed text-failure-ink">{node.error}</small>}</span><span className="pt-0.5 text-muted">{node.estimatedCostUsd !== null ? money(node.estimatedCostUsd) : node.status === "pending" ? "Waiting" : node.status}</span></li>)}</ol>}
        <div className="mb-3 flex items-center gap-2"><h3 className="m-0 flex-1 type-sm font-medium">Results <span className="ml-1 text-muted">{allResults.length}</span></h3>{compare.length > 0 && <button className={CANVAS_BUTTON} type="button" onClick={() => expanded ? setCompare([]) : onExpand()}>{expanded ? "Show all" : `Compare ${compare.length}`}</button>}</div>
        {results.length ? <div className={`grid gap-4 ${expanded ? results.length > 2 ? "grid-cols-2 @min-canvas-wide/canvas:grid-cols-3" : "grid-cols-2" : "grid-cols-1"}`}>{results.map((result) => <article key={result.id} className={`overflow-hidden rounded-inner border bg-card ${compare.includes(result.id) ? "border-brand" : "border-divider"}`}><div className="canvas-result-preview flex min-h-36 items-center justify-center bg-field"><ResultMedia result={result} /></div><div className="flex flex-col gap-2 p-3"><strong className="truncate type-xs font-medium">{result.label}</strong><div className="flex items-center gap-2"><label className="flex flex-1 cursor-pointer items-center gap-2 type-xs text-muted"><input type="checkbox" checked={compare.includes(result.id)} onChange={() => setCompare((current) => current.includes(result.id) ? current.filter((id) => id !== result.id) : [...current, result.id])} />Compare</label>{(result.asset || result.text) && <button className={CANVAS_BUTTON} type="button" onClick={() => onUseResult(result)}><ArrowUpRight size={12} />Use</button>}</div></div></article>)}</div> : <p className="m-0 flex items-center gap-2 rounded-inner bg-field p-4 type-xs leading-relaxed text-muted"><FileText size={15} className="shrink-0" />{selectedRun.mode === "preview" ? "Generation previews do not create media." : "Completed outputs will appear here."}</p>}
      </div>}
    </div>}
  </aside>;
}
